### PR TITLE
Fix wrong bz2 dependency in Windows .pc pkg-config file

### PR DESCRIPTION
**Pull request by traversaro**
This PR fixes the issue reported in https://github.com/conda-forge/libzip-feedstock/issues/20 .

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
If the project is ever updated to the latest version, the patch will need to be updated with this one: 
https://github.com/traversaro/libzip/commit/54bbb4e5919eb5860df4f7bab4d208db2014e760.patch .

**Comment by traversaro** [comment]
The only listed mantainer is @ceholden but he does not seem really active, what is the correct way to proceed in this case. cc @conda-forge/help-c-cpp . If it helps, I will be happy to be added as a mantainer.

**Comment by traversaro** [comment]
Upstream issue: https://github.com/ignitionrobotics/docs/issues/96 .

**Comment by traversaro** [comment]
cc @wolfv (this fixes an issue in ignition-fuel-tools when compiled when pkg-config is installed)

**Comment by wolfv** [comment]
Hi @traversaro usually we wait for 3 days for the maintainers to respond. Let's see if @ceholden responds today, and if not we can merge with core-rights.
Would be great to get a later version in as well. I might have a look.

**Comment by traversaro** [comment]
> Hi @traversaro usually we wait for 3 days for the maintainers to respond. Let's see if @ceholden responds today, and if not we can merge with core-rights.

Perfect, if that is the policy we can also wait for full 3 days, no problem on my side.

**Comment by traversaro** [comment]
As there was only one maintainer that seems currently unavailable, I added myself as a mantainer as part of this PR.

**Comment by wolfv** [comment]
thanks @traversaro for picking this up!

I think we could release a new version, but we might have issues with the DLL compatibilities ... 

The usual way is to globally pin a version in the conda-forge pinnings file: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml and then start a "migrator" for all projects depending on libzip.

I am just mentioning this in case you wanted to release a newer version, I don't know what other downstream packages depend on libzip.

**Comment by traversaro** [comment]
> 
> 
> thanks @traversaro for picking this up!
> 
> I think we could release a new version, but we might have issues with the DLL compatibilities ...
> 
> The usual way is to globally pin a version in the conda-forge pinnings file: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml and then start a "migrator" for all projects depending on libzip.
> 
> I am just mentioning this in case you wanted to release a newer version, I don't know what other downstream packages depend on libzip.

Thanks, this is good to know. I will check the ABI policy of libzip and understand if it make sense to add a `run_exports`  for this repo (as it is installing shared libraries). Hopefully if the ABI policy of libzip is to break only on major version change, we could bump the minor version without worrying too much of creating problems downstream.

**Comment by wolfv** [comment]
by using `mamba repoquery whoneeds libzip -c conda-forge` I was able to find that only qgis and libignition-fuel-tools4 seem to depend on `libzip`.

Just as a FYI

**Comment by traversaro** [comment]
> 
> 
> > thanks @traversaro for picking this up!
> > I think we could release a new version, but we might have issues with the DLL compatibilities ...
> > The usual way is to globally pin a version in the conda-forge pinnings file: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml and then start a "migrator" for all projects depending on libzip.
> > I am just mentioning this in case you wanted to release a newer version, I don't know what other downstream packages depend on libzip.
> 
> Thanks, this is good to know. I will check the ABI policy of libzip and understand if it make sense to add a `run_exports` for this repo (as it is installing shared libraries). Hopefully if the ABI policy of libzip is to break only on major version change, we could bump the minor version without worrying too much of creating problems downstream.

According to https://github.com/nih-at/libzip/issues/218 we should be safe to go, we just need to add a run_exports similar to the one of [ignitionrobotics projects](https://ignitionrobotics.org/).

**Pull request merged**
