### PR TITLE
General cleanup

### PR DESCRIPTION
**Pull request by traversaro**
* Bump version to 1.7.3
* Add appropriate run_exports coherent with the ABI policy of the library
* Update pkg-config patch to be compatible with 1.7.3
* Update perl pin
* Be explicit on the enabled/disabled dependencies, otherwise libzip enables all of them by defaults and ignores without raising errors the dependencies that it does not found.

Based on the discussion in https://github.com/conda-forge/libzip-feedstock/pull/21#issuecomment-726715435 . 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
looks good to me!

**Comment by traversaro** [comment]
> 
> 
> looks good to me!

Sorry for the newbie question, but there is any policy here for merging? Should I wait on an explicit review from someone else or some other maintainer, or I can just merge? There is even here the 3 days rule you mentioned for PR from non-maintainers?

**Comment by wolfv** [comment]
No, you're a maintainer now, so you can do as you please :)

**Pull request merged**
