### PR TITLE
Uniform Windows builds with Unix ones and cleanup

### PR DESCRIPTION
**Pull request by traversaro**
See https://github.com/conda-forge/libzip-feedstock/pull/38#issuecomment-1704983481 for the context.

In a nutshell:
* Use on Windows the same CMake options of Linux/macOS. This means disabling lzma and zstd support on Windows (see https://github.com/conda-forge/libzip-feedstock/issues/39)
* Use Ninja instead of NMake on Windows
* ~Run tests on Windows~ Apparently tests are not running neither on Windows or Unix, see https://github.com/conda-forge/libzip-feedstock/issues/41 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
fyi @peci1

**Comment by peci1** [comment]
Thanks, LGTM!

**Comment by peci1** [comment]
Argh... ssl library is named libssl.lib on windows, so it also needs the renaming patch...

**Comment by peci1** [comment]
And the dynamic library is called libssl-3-x64.dll ...

**Comment by peci1** [comment]
and crypto -> libcrypto

**Comment by peci1** [comment]
With these two renames, gz-fuel_tools9 compiles on Windows.

**Comment by peci1** [comment]
```
-- Looking for OGRE using the name: OGRE2
--   ! OGRE2 not found
-- Looking for OGRE using the name: OGRE-Next
--   + component HlmsPbs: found
--   + component HlmsUnlit: found
--   + component Overlay: found
--   + component PlanarReflections: found
-- Looking for GzOGRE2 - found
```

**Comment by peci1** [comment]
I've tested 1.10.0-3 now and gz-fuel_tools9 build correctly. Thanks for the updates!

**Pull request merged**
